apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend # deployment will be manage(create, upgrade, delete) pods with labels created in TEMPLATES
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:0.7.1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "75m"
              memory: "128Mi"
            limits:
              cpu: "150m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 7
            periodSeconds: 10
      tolerations:
        - key: "frontend"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

