


# This file shouldn't be pushed to GitHub, but I pushed it as an example because it's not a real production application. Be careful!!!!!!!!


apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  PROJECT_NAME: "kube-essentials"
  SECRET_KEY: "verysecret"
  FIRST_SUPERUSER: "admin@example.com"
  FIRST_SUPERUSER_PASSWORD: "aUZZVGJZd09VWUtpZHhHdXhBNmZLQT09" # Should be at least 8 characters
  POSTGRES_SERVER: "postgres-postgresql.postgres" # Use the postgres-postgresql service located in the postrges namespace
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "iF7tuTTR9h" # Find it in the secret in the postgres namespace
